// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/avatar_proto.proto

package avatar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Avatar struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Avatar) Reset()         { *m = Avatar{} }
func (m *Avatar) String() string { return proto.CompactTextString(m) }
func (*Avatar) ProtoMessage()    {}
func (*Avatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c872a618e0c11a, []int{0}
}

func (m *Avatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Avatar.Unmarshal(m, b)
}
func (m *Avatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Avatar.Marshal(b, m, deterministic)
}
func (m *Avatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Avatar.Merge(m, src)
}
func (m *Avatar) XXX_Size() int {
	return xxx_messageInfo_Avatar.Size(m)
}
func (m *Avatar) XXX_DiscardUnknown() {
	xxx_messageInfo_Avatar.DiscardUnknown(m)
}

var xxx_messageInfo_Avatar proto.InternalMessageInfo

func (m *Avatar) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Avatar) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Avatar) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AvatarRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarRequest) Reset()         { *m = AvatarRequest{} }
func (m *AvatarRequest) String() string { return proto.CompactTextString(m) }
func (*AvatarRequest) ProtoMessage()    {}
func (*AvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c872a618e0c11a, []int{1}
}

func (m *AvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarRequest.Unmarshal(m, b)
}
func (m *AvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarRequest.Marshal(b, m, deterministic)
}
func (m *AvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarRequest.Merge(m, src)
}
func (m *AvatarRequest) XXX_Size() int {
	return xxx_messageInfo_AvatarRequest.Size(m)
}
func (m *AvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarRequest proto.InternalMessageInfo

type AvatarResponse struct {
	Data                 []*Avatar `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AvatarResponse) Reset()         { *m = AvatarResponse{} }
func (m *AvatarResponse) String() string { return proto.CompactTextString(m) }
func (*AvatarResponse) ProtoMessage()    {}
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0c872a618e0c11a, []int{2}
}

func (m *AvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarResponse.Unmarshal(m, b)
}
func (m *AvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarResponse.Marshal(b, m, deterministic)
}
func (m *AvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarResponse.Merge(m, src)
}
func (m *AvatarResponse) XXX_Size() int {
	return xxx_messageInfo_AvatarResponse.Size(m)
}
func (m *AvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarResponse proto.InternalMessageInfo

func (m *AvatarResponse) GetData() []*Avatar {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Avatar)(nil), "whatw_golang_laravel.Avatar")
	proto.RegisterType((*AvatarRequest)(nil), "whatw_golang_laravel.AvatarRequest")
	proto.RegisterType((*AvatarResponse)(nil), "whatw_golang_laravel.AvatarResponse")
}

func init() {
	proto.RegisterFile("proto/avatar_proto.proto", fileDescriptor_b0c872a618e0c11a)
}

var fileDescriptor_b0c872a618e0c11a = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2c, 0x4b, 0x2c, 0x49, 0x2c, 0x8a, 0x07, 0x73, 0xf4, 0xc0, 0xa4, 0x90, 0x48,
	0x79, 0x46, 0x62, 0x49, 0x79, 0x7c, 0x7a, 0x7e, 0x4e, 0x62, 0x5e, 0x7a, 0x7c, 0x4e, 0x62, 0x51,
	0x62, 0x59, 0x6a, 0x8e, 0x92, 0x0b, 0x17, 0x9b, 0x23, 0x58, 0xad, 0x10, 0x1f, 0x17, 0x53, 0x66,
	0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x08, 0x17, 0x6b, 0x66,
	0x6e, 0x62, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x03, 0x12, 0x2d, 0x28,
	0xca, 0x4c, 0x4e, 0x95, 0x60, 0x06, 0x2b, 0x84, 0x70, 0x94, 0xf8, 0xb9, 0x78, 0x21, 0xa6, 0x04,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x39, 0x71, 0xf1, 0xc1, 0x04, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x0c, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8,
	0x8d, 0x64, 0xf4, 0xb0, 0xb9, 0x46, 0x0f, 0xaa, 0x07, 0xac, 0xd2, 0x28, 0x13, 0x66, 0x68, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x04, 0x17, 0xa7, 0x7b, 0x6a, 0x09, 0xd4, 0xb9, 0xca,
	0x78, 0x4d, 0x80, 0x38, 0x43, 0x4a, 0x05, 0xbf, 0x22, 0x88, 0xd3, 0x94, 0x18, 0x9c, 0x84, 0xa3,
	0x04, 0x0b, 0x92, 0xf4, 0xa1, 0xd2, 0xd0, 0xc0, 0x4b, 0x62, 0x03, 0x87, 0x9b, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x13, 0x1c, 0xbc, 0xe5, 0x53, 0x01, 0x00, 0x00,
}
