// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/question_proto.proto

package question

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Difficulty           string   `protobuf:"bytes,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Question             string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	CorrectAnswer        string   `protobuf:"bytes,4,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	IncorrectAnswer1     string   `protobuf:"bytes,5,opt,name=incorrect_answer1,json=incorrectAnswer1,proto3" json:"incorrect_answer1,omitempty"`
	IncorrectAnswer2     string   `protobuf:"bytes,6,opt,name=incorrect_answer2,json=incorrectAnswer2,proto3" json:"incorrect_answer2,omitempty"`
	IncorrectAnswer3     string   `protobuf:"bytes,7,opt,name=incorrect_answer3,json=incorrectAnswer3,proto3" json:"incorrect_answer3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_0789342f327d6024, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Question) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *Question) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Question) GetCorrectAnswer() string {
	if m != nil {
		return m.CorrectAnswer
	}
	return ""
}

func (m *Question) GetIncorrectAnswer1() string {
	if m != nil {
		return m.IncorrectAnswer1
	}
	return ""
}

func (m *Question) GetIncorrectAnswer2() string {
	if m != nil {
		return m.IncorrectAnswer2
	}
	return ""
}

func (m *Question) GetIncorrectAnswer3() string {
	if m != nil {
		return m.IncorrectAnswer3
	}
	return ""
}

type QuestionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionRequest) Reset()         { *m = QuestionRequest{} }
func (m *QuestionRequest) String() string { return proto.CompactTextString(m) }
func (*QuestionRequest) ProtoMessage()    {}
func (*QuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0789342f327d6024, []int{1}
}

func (m *QuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionRequest.Unmarshal(m, b)
}
func (m *QuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionRequest.Marshal(b, m, deterministic)
}
func (m *QuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionRequest.Merge(m, src)
}
func (m *QuestionRequest) XXX_Size() int {
	return xxx_messageInfo_QuestionRequest.Size(m)
}
func (m *QuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionRequest proto.InternalMessageInfo

type QuestionResponse struct {
	Data                 []*Question `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuestionResponse) Reset()         { *m = QuestionResponse{} }
func (m *QuestionResponse) String() string { return proto.CompactTextString(m) }
func (*QuestionResponse) ProtoMessage()    {}
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0789342f327d6024, []int{2}
}

func (m *QuestionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionResponse.Unmarshal(m, b)
}
func (m *QuestionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionResponse.Marshal(b, m, deterministic)
}
func (m *QuestionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionResponse.Merge(m, src)
}
func (m *QuestionResponse) XXX_Size() int {
	return xxx_messageInfo_QuestionResponse.Size(m)
}
func (m *QuestionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionResponse proto.InternalMessageInfo

func (m *QuestionResponse) GetData() []*Question {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Question)(nil), "whatw_golang_laravel.Question")
	proto.RegisterType((*QuestionRequest)(nil), "whatw_golang_laravel.QuestionRequest")
	proto.RegisterType((*QuestionResponse)(nil), "whatw_golang_laravel.QuestionResponse")
}

func init() {
	proto.RegisterFile("proto/question_proto.proto", fileDescriptor_0789342f327d6024)
}

var fileDescriptor_0789342f327d6024 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x6d, 0xf7, 0xc7, 0x79, 0x87, 0x73, 0x8b, 0x0a, 0xa1, 0x0f, 0xa3, 0x14, 0x26, 0x05,
	0xa1, 0x63, 0xed, 0x27, 0xd0, 0x07, 0x7d, 0xb6, 0xbe, 0xf9, 0x60, 0xc9, 0xda, 0x6c, 0x06, 0x4a,
	0xd2, 0xa5, 0xd9, 0x8a, 0xef, 0x7e, 0x70, 0x21, 0xed, 0x32, 0x85, 0xc0, 0x5e, 0x02, 0xf7, 0xdc,
	0x5f, 0x6e, 0x6e, 0x0e, 0x07, 0xbc, 0x4a, 0x0a, 0x25, 0x96, 0xbb, 0x3d, 0xad, 0x15, 0x13, 0x3c,
	0xd3, 0x65, 0xa4, 0x4f, 0x74, 0xd7, 0x7c, 0x11, 0xd5, 0x64, 0x5b, 0x51, 0x12, 0xbe, 0xcd, 0x4a,
	0x22, 0xc9, 0x81, 0x96, 0xc1, 0x8f, 0x0b, 0xa3, 0xb7, 0x0e, 0x47, 0x13, 0x70, 0x59, 0x81, 0x1d,
	0xdf, 0x09, 0x07, 0xa9, 0xcb, 0x0a, 0x34, 0x07, 0x28, 0xd8, 0x66, 0xc3, 0xf2, 0x7d, 0xa9, 0xbe,
	0xb1, 0xeb, 0x3b, 0xe1, 0x55, 0xfa, 0x47, 0x41, 0x1e, 0x8c, 0x8e, 0x4f, 0xe1, 0x9e, 0xee, 0x9a,
	0x1a, 0x2d, 0x60, 0x92, 0x0b, 0x29, 0x69, 0xae, 0x32, 0xc2, 0xeb, 0x86, 0x4a, 0xdc, 0xd7, 0xc4,
	0x75, 0xa7, 0x3e, 0x69, 0x11, 0x3d, 0xc2, 0x8c, 0xf1, 0xff, 0xe0, 0x0a, 0x0f, 0x34, 0x39, 0x35,
	0x8d, 0x96, 0x5d, 0xd9, 0xe0, 0x18, 0x0f, 0xad, 0x70, 0x6c, 0x83, 0x13, 0x7c, 0x69, 0x85, 0x93,
	0x60, 0x06, 0x37, 0x47, 0x17, 0x52, 0xaa, 0xff, 0x10, 0xbc, 0xc0, 0xf4, 0x24, 0xd5, 0x95, 0xe0,
	0x35, 0x45, 0x31, 0xf4, 0x0b, 0xa2, 0x08, 0x76, 0xfc, 0x5e, 0x38, 0x8e, 0xe7, 0x91, 0xcd, 0xd2,
	0xc8, 0xdc, 0xd2, 0x6c, 0xbc, 0x3b, 0x8d, 0x7e, 0xa7, 0xf2, 0xc0, 0x72, 0x8a, 0x3e, 0x61, 0xfc,
	0x4a, 0x95, 0xb1, 0x7d, 0x71, 0x66, 0x4e, 0xbb, 0x90, 0xf7, 0x70, 0x0e, 0x6b, 0x97, 0x0c, 0x2e,
	0x9e, 0xef, 0x3f, 0x6e, 0xab, 0xf5, 0xb2, 0x03, 0x4c, 0x1a, 0xd6, 0x43, 0x1d, 0x84, 0xe4, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xcf, 0x6a, 0xe8, 0x98, 0x26, 0x02, 0x00, 0x00,
}
